"""User Personal Details Table created

Revision ID: 5e8cfcdfa7ac
Revises: 13bce2cf7718
Create Date: 2026-05-30 16:50:02.192779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e8cfcdfa7ac'
down_revision: Union[str, Sequence[str], None] = '13bce2cf7718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
