"""Updated banking details table

Revision ID: 9e5cb809024c
Revises: e4f36ed6d688
Create Date: 2026-05-31 21:25:04.334688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5cb809024c'
down_revision: Union[str, Sequence[str], None] = 'e4f36ed6d688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banking_details', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('banking_details', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banking_details', 'updated_at')
    op.drop_column('banking_details', 'created_at')
    # ### end Alembic commands ###
